apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.letsencrypt.env }}
spec:
  acme:
    server: {{ .Values.letsencrypt.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.letsencrypt.env }}
    http01: {}
---